# Generated by Django 3.0.6 on 2020-05-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=10000)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Ultra Tech Preference',
                'verbose_name_plural': 'Ultra Tech Preferences',
                'db_table': 'ultra_tech_preferences',
            },
        ),
    ]
