# Generated by Django 3.0.6 on 2020-06-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_analysis', '0002_delete_simi_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemical_similarity_data',
            old_name='path',
            new_name='Path',
        ),
        migrations.AddField(
            model_name='chemical_similarity_data',
            name='toll',
            field=models.BooleanField(null=True),
        ),
    ]
