# Generated by Django 3.0.6 on 2020-06-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_analysis', '0003_auto_20200612_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical_similarity_data',
            name='toll',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=32),
        ),
    ]
