# Generated by Django 3.0.6 on 2020-06-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_analysis', '0004_auto_20200623_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical_similarity_data',
            name='toll',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=32),
        ),
    ]
