f=open("venky.txt","a")
f.write("vennnnvenky venkat")
#print(f.read())
print("file name:",f.name)
print("file mode :",f.mode)
print("file readable :",f.readable())
print("file writeble :",f.writable())
print("file closed :",f.closed)
f.close()
print("file closed :",f.closed)
