# Generated by Django 3.0.6 on 2020-07-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultratech_new_destination', '0002_auto_20200724_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refdata',
            name='city_code',
        ),
        migrations.RemoveField(
            model_name='refdata',
            name='direct_sto',
        ),
        migrations.RemoveField(
            model_name='refdata',
            name='hilly_per',
        ),
        migrations.RemoveField(
            model_name='refdata',
            name='nh_per',
        ),
        migrations.RemoveField(
            model_name='refdata',
            name='other_per',
        ),
        migrations.RemoveField(
            model_name='refdata',
            name='plain_per',
        ),
        migrations.RemoveField(
            model_name='refdata',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='refdata',
            name='sh_per',
        ),
        migrations.RemoveField(
            model_name='refdata',
            name='slab',
        ),
        migrations.RemoveField(
            model_name='refdata',
            name='truck_type',
        ),
    ]
