# Generated by Django 3.0.6 on 2020-07-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultratech_new_destination', '0003_auto_20200724_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='simi_predicted_ptpk',
        ),
        migrations.AddField(
            model_name='plantmapdata',
            name='similarity_predicted_ptpk',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
