# Generated by Django 3.0.6 on 2020-07-28 15:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultratech_new_destination', '0004_auto_20200724_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapAPIData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('geocode_latlong', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('distance_matrix', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('elev_url', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('elevation_extraction', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('plant_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_api_data', to='ultratech_new_destination.Destination')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
