# Generated by Django 3.0.6 on 2020-07-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultratech_new_destination', '0005_mapapidata'),
    ]

    operations = [
        migrations.AddField(
            model_name='similaritydata',
            name='city_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='similaritydata',
            name='total_restriction_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
