# Generated by Django 3.0.6 on 2020-08-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultratech_new_destination', '0006_auto_20200731_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantmapdata',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='similaritydata',
            name='i2_taluka_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='similaritydata',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
