# Generated by Django 3.0.6 on 2020-08-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultratech_new_destination', '0008_mapapidata_reverse_geocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantmapdata',
            name='comment_lead',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
