# Generated by Django 3.0.6 on 2020-08-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultratech_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=128, null=True)),
                ('plant', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('city_code', models.CharField(blank=True, max_length=128, null=True)),
                ('city_desc', models.CharField(blank=True, max_length=128, null=True)),
                ('simi_type', models.CharField(blank=True, max_length=128, null=True)),
                ('simi_city_code', models.CharField(blank=True, max_length=128, null=True)),
                ('simi_city_name', models.CharField(blank=True, max_length=128, null=True)),
                ('truck_type', models.IntegerField(blank=True, null=True)),
                ('direct_sto', models.CharField(blank=True, max_length=128, null=True)),
                ('mean_route_time_taken', models.FloatField(blank=True, null=True)),
                ('mean_ele', models.FloatField(blank=True, null=True)),
                ('sd_ele', models.FloatField(blank=True, null=True)),
                ('nh_per_ref', models.FloatField(blank=True, null=True)),
                ('sh_per_ref', models.FloatField(blank=True, null=True)),
                ('other_per_ref', models.FloatField(blank=True, null=True)),
                ('lead', models.FloatField(blank=True, null=True)),
                ('ptpk', models.FloatField(blank=True, null=True)),
                ('plain_per_ref', models.FloatField(blank=True, null=True)),
                ('hilly_per_ref', models.FloatField(blank=True, null=True)),
                ('onward_travel', models.FloatField(blank=True, null=True)),
                ('return_travel', models.FloatField(blank=True, null=True)),
                ('idle_time_cust', models.FloatField(blank=True, null=True)),
                ('slab', models.CharField(blank=True, max_length=128, null=True)),
                ('cityno', models.CharField(blank=True, max_length=128, null=True)),
                ('simi_coeff', models.FloatField(blank=True, null=True)),
                ('ptpk_pred', models.FloatField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=128, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('batch', models.FloatField(blank=True, null=True)),
                ('source_lat', models.FloatField(blank=True, null=True)),
                ('source_long', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('pred_base_freight', models.FloatField(blank=True, null=True)),
                ('impact', models.FloatField(blank=True, null=True)),
                ('base_freight', models.FloatField(blank=True, null=True)),
                ('taluka', models.CharField(blank=True, max_length=128, null=True)),
                ('i2_taluka_desc', models.CharField(blank=True, max_length=128, null=True)),
                ('t_type', models.CharField(blank=True, max_length=128, null=True)),
                ('full_plant_name', models.CharField(blank=True, max_length=128, null=True)),
                ('simi_city', models.CharField(blank=True, max_length=128, null=True)),
                ('full_city', models.CharField(blank=True, max_length=128, null=True)),
                ('route_1', models.CharField(blank=True, max_length=128, null=True)),
                ('route', models.CharField(blank=True, max_length=128, null=True)),
                ('route_2', models.CharField(blank=True, max_length=128, null=True)),
                ('plant_name', models.CharField(blank=True, max_length=128, null=True)),
                ('simi_route', models.CharField(blank=True, max_length=128, null=True)),
                ('total_restriction_time', models.FloatField(blank=True, null=True)),
                ('integration_flag', models.IntegerField(blank=True, null=True)),
                ('cluster_flag', models.IntegerField(blank=True, null=True)),
                ('union_flag', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'UltraTech Similarity Data',
                'verbose_name_plural': 'UltraTech Similarity Data',
            },
        ),
    ]
