# Generated by Django 3.0.6 on 2020-11-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultratech_analysis', '0002_similaritydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='similaritydata',
            name='depot_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='similaritydata',
            name='depot_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='similaritydata',
            name='district_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='similaritydata',
            name='district_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
